name: Replication Helper

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  
jobs:
  
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          cache: "pip"
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev
          pip install genbadge[tests,coverage]
      - name: Test with pytest
        run: |
          uv run pytest -s --cov=. --cov-branch --cov-config=.coveragerc --doctest-modules --junitxml=htmlcov/junit.xml --cov-report=html --cov-report=xml --cov-report=json
      - name: Generate badges
        run: |
          genbadge tests -i htmlcov/junit.xml -o htmlcov/junit-badge.svg
          genbadge coverage -i ./coverage.xml -o htmlcov/coverage-badge.svg
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './htmlcov/'
        
  deploy-gh-pages:
    if: github.ref == 'refs/heads/main'
    needs: test-coverage
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - name: deploy to Github Pages
        uses: actions/deploy-pages@v4
        id: deployment
  
  matrix-prep:
    runs-on: ubuntu-latest

    outputs: 
      include: ${{steps.gen.outputs.include}}
      
    steps:
      - id: gen
        run: |          
          declare -a pgversion=( 14 15 16 17 )
          
          include_json=$(
            {
              for i in "${pgversion[@]}"
              do
                for j in "${pgversion[@]}"
                do
                  if [ "$i" -le "$j" ]; then
                    jq -n -c "{primary:$i,secondary:$j}"
                  fi
                done
              done
            } | jq -s -c .
          )
          
          echo "include=$include_json" >> "$GITHUB_OUTPUT"

  matrix-test:
    needs: matrix-prep
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix: 
        include: ${{fromJSON(needs.matrix-prep.outputs.include)}}
    
    name: " PG-${{matrix.primary}}->PG-${{matrix.secondary}} "

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          cache: "pip"
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev
          pip install genbadge[tests,coverage]
      - name: Setup PostgreSQL
        uses: tj-actions/install-postgresql@v3
        with:
          postgresql-version: ${{matrix.secondary}}
      - name: Test with pytest
        env:
          POSTGRES_PRIMARY_VERSION: ${{matrix.primary}}
          POSTGRES_SECONDARY_VERSION: ${{matrix.secondary}}
        run: |
          uv run pytest -s 