# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Replication Helper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  matrix-prep:
    runs-on: ubuntu-latest

    outputs: 
      include: ${{steps.gen.outputs.include}}
      
    steps:
      - id: gen
        run: |          
          declare -a pgversion=( 14 15 16 17 )
          
          include_json=$(
            {
              for i in "${pgversion[@]}"
              do
                for j in "${pgversion[@]}"
                do
                  if [ "$i" -le "$j" ]; then
                    jq -n -c "{origin:$i,destination:$j}"
                  fi
                done
              done
            } | jq -s -c .
          )
          
          echo "include=$include_json" >> "$GITHUB_OUTPUT"

  build:
    needs: matrix-prep
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix: 
        include: ${{fromJSON(needs.matrix-prep.outputs.include)}}
    
    name: " PG-${{matrix.origin}}->PG-${{matrix.destination}} "

    steps:
    - uses: actions/checkout@v4
    - name: Setup PostgreSQL
      uses: tj-actions/install-postgresql@v3
      with:
        postgresql-version: ${{matrix.destination}}
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"
    - name: Install dependencies
      run: |
        uv sync --locked --all-extras --dev
        pip install genbadge[tests,coverage]
    - name: Test with pytest
      env:
        POSTGRES_ORIGIN_VERSION: ${{matrix.origin}}
        POSTGRES_DESTINATION_VERSION: ${{matrix.destination}}
      run: |
        uv run pytest -s --cov=. --cov-branch --cov-config=.coveragerc --doctest-modules --junitxml=htmlcov/junit.xml --cov-report=html --cov-report=xml --cov-report=json
    - name: Generate badges
      if: github.ref == 'refs/heads/main'
      run: |
        genbadge tests -i htmlcov/junit.xml -o coverage/junit-badge.svg
        genbadge coverage -i ./coverage.xml -o coverage/coverage-badge.svg
    - name: commit badges
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: badges
        folder: coverage